# Goal

geometry_msgs/Pose goal
string move_type  # 'hold', 'drive', 'skid', 'circle'
geometry_msgs/Point focus

---
# Result

string failure_reason

---
# Feedback

string behavior
int64 tree_size
bool tracking
float64[] distance
float64 time_till_next_branch
